"""Fetch the Times Gate font catalog and write it as Markdown (with samples).

The cloud endpoint ``Device/GetTimeDialFontList`` returns the device-scoped
font registry (the ``font`` ids usable in ``Draw/SendHttpItemList``), with
per-font name, glyph size, download URL and — crucially — the exact
``charset``. Note the endpoint has been flaky in the past: an empty
``FontList`` usually means the DeviceId/DeviceType params were omitted, but
retry later if it persists.

Font files are served from Divoom's CDN (``https://f.divoom-gz.com/`` +
``fontUrl``) but are stored in an encrypted/proprietary container (verified:
no TTF magic bytes), so local preview rendering is not possible. For visual
samples, use ``show_font_samples.py`` to display batches on the device and
photograph them. (The plain-TTF catalog on appchina's ``GetTimeDialFontV2``
is the *Frame* family's separate registry — same ids, different fonts — and
does NOT apply to the Times Gate.)

Usage:
    python get_font_list.py [DEVICE_ID] [OUTPUT_DIR]

DEVICE_ID defaults to 0 (the catalog appears to be shared, but pass your own
id — from discovery / the Divoom app — to be safe). OUTPUT_DIR defaults to
the repo's docs/ directory; writes docs/FONTS_CATALOG.md.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request

URL = "https://app.divoom-gz.com/Device/GetTimeDialFontList"
CDN = "https://f.divoom-gz.com/"

TYPE_LABELS = {0: "bitmap", 1: "vector", 3: "image glyph"}

# Style hints derived from the font *name* (the files are encrypted, so this
# is the best available signal). Keyword → hint.
_STYLE_HINTS = [
    (("segment",), "7-segment/digital"),
    (("pixel", "8-bit", "8bit"), "pixel/8-bit"),
    (("serif", "宋体"), "serif"),
    (("圆", "round", "rounded"), "rounded"),
    (("hand", "手写", "script"), "handwriting"),
    (("bold", "粗"), "bold"),
]


def style_hint(name: str) -> str:
    low = name.lower()
    return ", ".join(h for keys, h in _STYLE_HINTS if any(k in low for k in keys))


def categories(charset: str, ftype: int) -> list[str]:
    """Functional buckets a font belongs to, from its (API) charset."""
    if not charset:
        # The classic bitmap "standard fonts" render general text.
        return ["full-text"] if ftype == 0 else ["unknown-charset"]
    cs = set(charset)
    has_digits = any(c.isdigit() for c in cs)
    lower = sum(c.islower() for c in cs)
    upper = sum(c.isupper() for c in cs)
    cats = []
    if lower >= 20 and upper >= 20 and len(cs & set("%.:-/")) >= 3:
        cats.append("full-text")
    elif lower >= 20 and upper >= 20:
        cats.append("letters-digits")
    elif upper >= 20:
        cats.append("caps-digits")
    if has_digits:
        if "%" in cs:
            cats.append("percent")
        if "." in cs:
            cats.append("decimals")
        if ":" in cs:
            cats.append("clock")
        if "$" in cs:
            cats.append("currency")
        if "c" in cs and "f" in cs and lower <= 4:
            cats.append("temperature")
        if cs <= set("0123456789"):
            cats.append("digits-only")
    return cats or ["other"]

_PREFERRED_SAMPLE = "Ab12.5%:-$"


def main() -> int:
    args = list(sys.argv[1:])
    device_id = int(args[0]) if args else 0
    out_dir = args[1] if len(args) > 1 else os.path.join(
        os.path.dirname(__file__), "..", "docs"
    )

    body = json.dumps({"DeviceId": device_id, "DeviceType": "LCD"}).encode()
    req = urllib.request.Request(URL, body, {"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310 - fixed Divoom host
        data = json.loads(resp.read())
    fonts = data.get("FontList", [])
    if not fonts:
        print("Empty FontList — endpoint flaky or params rejected; try again later.")
        return 1

    lines = [
        "# Times Gate font catalog (`Draw/SendHttpItemList` font ids)",
        "",
        f"Generated by `scripts/get_font_list.py` from `{URL}`",
        f"({len(fonts)} fonts). The `charset` column is authoritative: glyphs",
        "outside it are silently dropped by the device. Hand-verified test",
        "notes and photographed samples live in FONTS.md.",
        "",
        "Font files © Divoom (and their respective type foundries), served",
        f"from Divoom's CDN (`{CDN}` + the catalog's `fontUrl`). Note: the",
        "files are stored in an encrypted/proprietary container — they are",
        "NOT directly usable TTFs, so no local previews can be rendered.",
        "Use `scripts/show_font_samples.py` to display fonts on the device",
        "and photograph them instead.",
        "",
    ]

    # --- "pick a working font fast" section: functional lists ---------------
    CAT_LABELS = {
        "full-text": "Full text (upper+lower case, digits, symbols) — labels, any value",
        "letters-digits": "Letters + digits (few/no symbols) — unit text like `kWh`",
        "caps-digits": "UPPERCASE + digits — compact unit text like `W`, `KM`",
        "percent": "Digits with `%` — percentages",
        "decimals": "Digits with `.` — decimal values",
        "clock": "Digits with `:` — times/clocks",
        "currency": "Digits with `$` — currency",
        "temperature": "Digits with `c`/`f` — temperatures (`21c`)",
        "digits-only": "Bare digits only — integers",
        "unknown-charset": "Charset not published (try on device)",
        "other": "Other",
    }
    def height(f: dict) -> int:
        try:
            return int(f.get("high", 0))
        except (TypeError, ValueError):
            return 0

    def reps(members: list[dict]) -> str:
        """A few representative ids spanning small / card-safe / large sizes."""
        by_h = sorted(members, key=height)
        picks: list[dict] = []
        small = next((f for f in by_h if height(f) < 12), None)
        card = next((f for f in by_h if 12 <= height(f) <= 16), None)
        large = next((f for f in reversed(by_h) if height(f) > 16), None)
        for f in (small, card, large):
            if f is not None and f not in picks:
                picks.append(f)
        if not picks:
            picks = by_h[:2]
        return ", ".join(f"`{int(f['id'])}` ({height(f)}px)" for f in picks)

    by_cat: dict[str, list[dict]] = {}
    for f in fonts:
        for cat in categories(str(f.get("charset", "")), int(f.get("type", -1))):
            by_cat.setdefault(cat, []).append(f)
    lines += [
        "## Quick picks by use case",
        "",
        "A few representative ids per need (small · card-safe ~14px · large).",
        "For every size available, find the charset in the grouped table below.",
        "",
    ]
    for cat, label in CAT_LABELS.items():
        members = by_cat.get(cat)
        if members:
            lines.append(f"- **{label}**: {reps(members)}")

    # --- grouped catalog: one row per charset (only the size differs) --------
    def usefulness(cs: str) -> tuple:
        s = set(cs)
        return (
            any(c.islower() for c in s),   # full text first
            any(c.isupper() for c in s),
            len(s - set("0123456789")),    # more symbols = richer
            len(s),
        )

    groups: dict[str, list[dict]] = {}
    for f in fonts:
        groups.setdefault(str(f.get("charset", "")), []).append(f)

    lines += [
        "",
        "## Fonts grouped by charset",
        "",
        "Fonts that support the same glyphs are listed together — they differ",
        "only in size, so pick the id whose height fits your layout (the card",
        "default is 14px). Glyphs outside the charset are dropped silently.",
        "",
        "| Supported glyphs (charset) | Available as `id` (height) |",
        "|---|---|",
    ]
    for cs in sorted(groups, key=usefulness, reverse=True):
        members = sorted(groups[cs], key=height)
        ids = ", ".join(f"`{int(f['id'])}` ({height(f)}px)" for f in members)
        shown = cs.replace("|", "\\|")
        if not shown:
            shown = "*(unpublished — general bitmap text)*"
        elif len(shown) > 52:
            shown = shown[:52] + "…"
        lines.append(f"| `{shown}` | {ids} |")

    lines += [
        "",
        "Need an exact size, style, or download URL for a specific id? Those",
        "columns are in the raw endpoint response; re-run the generator or query",
        f"`{URL}` with `{{DeviceId, DeviceType:\"LCD\"}}` directly.",
    ]

    path = os.path.join(out_dir, "FONTS_CATALOG.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Wrote {path} ({len(fonts)} fonts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
