"""Fetch the Divoom Times Gate face (ClockId) catalogs and print them as Markdown.

Adapted from gickowtf/pixoo-homeassistant's scripts/get_clock_ids.py (MIT) for
the Times Gate, which has two catalogs:
  * per-screen faces  — Channel/GetDialList with DeviceType="LCD"
  * whole-device faces — Channel/Get5LcdClockListForCommon (needs a DeviceId)

Usage:
    python get_face_ids.py [DEVICE_ID] > FACES.md

DEVICE_ID (from discovery / the Divoom app) is optional; without it the
whole-device (Overall Display) section is skipped. All calls hit Divoom's cloud.
"""
from __future__ import annotations

import json
import sys
import urllib.request

BASE = "https://app.divoom-gz.com"


def _post(path: str, body: dict) -> dict:
    req = urllib.request.Request(
        BASE + path, data=json.dumps(body).encode(), headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310 - fixed Divoom host
        return json.loads(resp.read().decode())


def per_screen_faces() -> dict[str, dict[int, str]]:
    """{category: {clock_id: name}} for single-screen faces."""
    out: dict[str, dict[int, str]] = {}
    types = _post("/Channel/GetDialType", {"DeviceType": "LCD"}).get("DialTypeList", [])
    for dial_type in types:
        ids: dict[int, str] = {}
        page, count = 1, 30
        while count == 30 and page <= 50:  # safety cap
            resp = _post(
                "/Channel/GetDialList",
                {"DialType": dial_type, "DeviceType": "LCD", "Page": page},
            )
            dials = resp.get("DialList", [])
            count = len(dials)
            page += 1
            for d in dials:
                ids[d["ClockId"]] = d.get("Name", "")
        if ids:
            out[dial_type] = dict(sorted(ids.items()))
    return out


def whole_faces(device_id: int) -> dict[int, str]:
    """{clock_id: name} for whole-device (Overall Display) faces."""
    out: dict[int, str] = {}
    page, count = 1, 30
    while count == 30 and page <= 50:
        resp = _post(
            "/Channel/Get5LcdClockListForCommon", {"DeviceId": device_id, "Page": page}
        )
        clocks = resp.get("ClockList", [])
        count = len(clocks)
        page += 1
        for c in clocks:
            out[int(c["ClockId"])] = c.get("ClockName", "")
    return dict(sorted(out.items()))


def main() -> None:
    device_id = int(sys.argv[1]) if len(sys.argv) > 1 else 0

    print("# Divoom Times Gate — face IDs\n")
    print("Generated by `scripts/get_face_ids.py`. `clock_id` values for use in")
    print("the integration's faces list, `page_type: clock`, and `set_clock_face`.\n")

    if device_id:
        whole = whole_faces(device_id)
        print(f"## Overall Display faces (whole device, {len(whole)})\n")
        print("One face spanning all 5 screens (`Set5LcdWholeClockId`).\n")
        for cid, name in whole.items():
            print(f"- `{cid}` — {name}")
        print()
    else:
        print("## Overall Display faces\n\n_(pass a DeviceId to include these)_\n")

    cats = per_screen_faces()
    total = sum(len(v) for v in cats.values())
    print(f"## Per-screen faces ({total} across {len(cats)} categories)\n")
    print("Single-screen faces (`SetClockSelectId` / `Face:` in a Screen select).\n")
    for cat, ids in cats.items():
        print(f"### {cat}\n")
        for cid, name in ids.items():
            print(f"- `{cid}` — {name}")
        print()


if __name__ == "__main__":
    main()
