"""Fetch the Divoom Times Gate face (ClockId) catalogs and write them as Markdown.

Adapted from gickowtf/pixoo-homeassistant's scripts/get_clock_ids.py (MIT) for
the Times Gate, which has two DISJOINT catalogs (see docs/API.md §2):
  * "Independent Display" — per-screen faces — Channel/GetDialType + GetDialList
    (DeviceType="LCD"). Selected with SetClockSelectId / SetEqPosition.
  * "Overall Display" — whole-device spanning faces — Channel/Get5LcdClockListForCommon
    (needs a DeviceId). Selected with Set5LcdWholeClockId.

Because the two are separate sources, this writes two separate documents:
  * docs/FACES_OVERALL.md      (Overall Display / whole dial)
  * docs/FACES_INDEPENDENT.md  (Independent Display / per-screen)

Usage:
    python get_face_ids.py [DEVICE_ID] [OUTPUT_DIR]

DEVICE_ID (from discovery / the Divoom app) is optional; without it the Overall
Display document is skipped (that catalog is device-scoped). OUTPUT_DIR defaults
to the repo's docs/ directory. All calls hit Divoom's cloud.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request

BASE = "https://app.divoom-gz.com"


def _post(path: str, body: dict) -> dict:
    req = urllib.request.Request(
        BASE + path, data=json.dumps(body).encode(), headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310 - fixed Divoom host
        return json.loads(resp.read().decode())


def per_screen_faces() -> dict[str, dict[int, str]]:
    """{category: {clock_id: name}} for single-screen faces."""
    out: dict[str, dict[int, str]] = {}
    types = _post("/Channel/GetDialType", {"DeviceType": "LCD"}).get("DialTypeList", [])
    for dial_type in types:
        ids: dict[int, str] = {}
        page, count = 1, 30
        while count == 30 and page <= 50:  # safety cap
            resp = _post(
                "/Channel/GetDialList",
                {"DialType": dial_type, "DeviceType": "LCD", "Page": page},
            )
            dials = resp.get("DialList", [])
            count = len(dials)
            page += 1
            for d in dials:
                ids[d["ClockId"]] = d.get("Name", "")
        if ids:
            out[dial_type] = dict(sorted(ids.items()))
    return out


def whole_faces(device_id: int) -> dict[int, str]:
    """{clock_id: name} for whole-device (Overall Display) faces."""
    out: dict[int, str] = {}
    page, count = 1, 30
    while count == 30 and page <= 50:
        resp = _post(
            "/Channel/Get5LcdClockListForCommon", {"DeviceId": device_id, "Page": page}
        )
        clocks = resp.get("ClockList", [])
        count = len(clocks)
        page += 1
        for c in clocks:
            out[int(c["ClockId"])] = c.get("ClockName", "")
    return dict(sorted(out.items()))


_HEADER = (
    "Generated by `scripts/get_face_ids.py`. `clock_id` values for use in the\n"
    "integration's faces list, `page_type: clock`, and `set_clock_face`.\n"
)


def _overall_doc(whole: dict[int, str]) -> str:
    lines = [
        "# Divoom Times Gate — Overall Display faces\n",
        _HEADER,
        '**Overall Display** (app UI) = whole dial: one face spanning all 5 screens,\n'
        "selected with `Channel/Set5LcdWholeClockId {ClockId}`. Catalog source:\n"
        "`Channel/Get5LcdClockListForCommon`. See `docs/API.md` §2.\n",
        f"## Faces (whole device, {len(whole)})\n",
    ]
    lines += [f"- `{cid}` — {name}" for cid, name in whole.items()]
    return "\n".join(lines) + "\n"


def _independent_doc(cats: dict[str, dict[int, str]]) -> str:
    total = sum(len(v) for v in cats.values())
    lines = [
        "# Divoom Times Gate — Independent Display faces\n",
        _HEADER,
        '**Independent Display** (app UI) = per-screen faces, selected with\n'
        "`Channel/SetClockSelectId` (or `SetEqPosition` for visualizers). Catalog\n"
        "source: `Channel/GetDialType` + `Channel/GetDialList`. See `docs/API.md` §2.\n",
        f"## Faces ({total} across {len(cats)} categories)\n",
    ]
    for cat, ids in cats.items():
        lines.append(f"### {cat}\n")
        lines += [f"- `{cid}` — {name}" for cid, name in ids.items()]
        lines.append("")
    return "\n".join(lines) + "\n"


def _write(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"wrote {path}")


def main() -> None:
    device_id = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    out_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs"
    )
    os.makedirs(out_dir, exist_ok=True)

    if device_id:
        whole = whole_faces(device_id)
        _write(os.path.join(out_dir, "FACES_OVERALL.md"), _overall_doc(whole))
    else:
        print("skipping FACES_OVERALL.md (pass a DeviceId to include Overall Display)")

    cats = per_screen_faces()
    _write(os.path.join(out_dir, "FACES_INDEPENDENT.md"), _independent_doc(cats))


if __name__ == "__main__":
    main()
