"""Fetch the Times Gate font catalog and write it as Markdown.

The cloud endpoint ``Device/GetTimeDialFontList`` returns the device-scoped
font registry (the ``font`` ids usable in ``Draw/SendHttpItemList``), with
per-font name, glyph size and — crucially — the exact ``charset``. Note the
endpoint has been flaky in the past: an empty ``FontList`` usually means the
DeviceId/DeviceType params were omitted, but retry later if it persists.

Usage:
    python get_font_list.py [DEVICE_ID] [OUTPUT_DIR]

DEVICE_ID defaults to 0 (the catalog appears to be shared, but pass your own
id — from discovery / the Divoom app — to be safe). OUTPUT_DIR defaults to
the repo's docs/ directory; writes docs/FONTS_CATALOG.md.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request

URL = "https://app.divoom-gz.com/Device/GetTimeDialFontList"

TYPE_LABELS = {0: "bitmap", 1: "vector", 3: "image glyph"}


def main() -> int:
    device_id = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    out_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(__file__), "..", "docs"
    )

    body = json.dumps({"DeviceId": device_id, "DeviceType": "LCD"}).encode()
    req = urllib.request.Request(URL, body, {"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310 - fixed Divoom host
        data = json.loads(resp.read())
    fonts = data.get("FontList", [])
    if not fonts:
        print("Empty FontList — endpoint flaky or params rejected; try again later.")
        return 1

    lines = [
        "# Times Gate font catalog (`Draw/SendHttpItemList` font ids)",
        "",
        f"Generated by `scripts/get_font_list.py` from `{URL}`",
        f"({len(fonts)} fonts). The `charset` column is authoritative: glyphs",
        "outside it are silently dropped by the device. Hand-verified test",
        "notes live in FONTS.md.",
        "",
        "| id | size | type | name | charset |",
        "|---|---|---|---|---|",
    ]
    for f in sorted(fonts, key=lambda f: int(f["id"])):
        charset = str(f.get("charset", "")).replace("|", "\\|")
        if len(charset) > 90:
            charset = charset[:90] + "…"
        lines.append(
            f"| {f['id']} | {f.get('width', '?')}×{f.get('high', '?')} "
            f"| {TYPE_LABELS.get(int(f.get('type', -1)), f.get('type'))} "
            f"| {str(f.get('name', '?')).replace('|', '\\|')} | `{charset}` |"
        )

    path = os.path.join(out_dir, "FONTS_CATALOG.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Wrote {path} ({len(fonts)} fonts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
