"""Fetch the Times Gate font catalog and write it as Markdown (with samples).

The cloud endpoint ``Device/GetTimeDialFontList`` returns the device-scoped
font registry (the ``font`` ids usable in ``Draw/SendHttpItemList``), with
per-font name, glyph size, download URL and — crucially — the exact
``charset``. Note the endpoint has been flaky in the past: an empty
``FontList`` usually means the DeviceId/DeviceType params were omitted, but
retry later if it persists.

Font files are served from Divoom's CDN (``https://f.divoom-gz.com/`` +
``fontUrl``) but are stored in an encrypted/proprietary container (verified:
no TTF magic bytes), so local preview rendering is not possible. For visual
samples, use ``show_font_samples.py`` to display batches on the device and
photograph them. (The plain-TTF catalog on appchina's ``GetTimeDialFontV2``
is the *Frame* family's separate registry — same ids, different fonts — and
does NOT apply to the Times Gate.)

Usage:
    python get_font_list.py [DEVICE_ID] [OUTPUT_DIR]

DEVICE_ID defaults to 0 (the catalog appears to be shared, but pass your own
id — from discovery / the Divoom app — to be safe). OUTPUT_DIR defaults to
the repo's docs/ directory; writes docs/FONTS_CATALOG.md.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request

URL = "https://app.divoom-gz.com/Device/GetTimeDialFontList"
CDN = "https://f.divoom-gz.com/"

TYPE_LABELS = {0: "bitmap", 1: "vector", 3: "image glyph"}

_PREFERRED_SAMPLE = "Ab12.5%:-$"


def main() -> int:
    args = list(sys.argv[1:])
    device_id = int(args[0]) if args else 0
    out_dir = args[1] if len(args) > 1 else os.path.join(
        os.path.dirname(__file__), "..", "docs"
    )

    body = json.dumps({"DeviceId": device_id, "DeviceType": "LCD"}).encode()
    req = urllib.request.Request(URL, body, {"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=15) as resp:  # noqa: S310 - fixed Divoom host
        data = json.loads(resp.read())
    fonts = data.get("FontList", [])
    if not fonts:
        print("Empty FontList — endpoint flaky or params rejected; try again later.")
        return 1

    lines = [
        "# Times Gate font catalog (`Draw/SendHttpItemList` font ids)",
        "",
        f"Generated by `scripts/get_font_list.py` from `{URL}`",
        f"({len(fonts)} fonts). The `charset` column is authoritative: glyphs",
        "outside it are silently dropped by the device. Hand-verified test",
        "notes and photographed samples live in FONTS.md.",
        "",
        "Font files © Divoom (and their respective type foundries), served",
        f"from Divoom's CDN (`{CDN}` + the catalog's `fontUrl`). Note: the",
        "files are stored in an encrypted/proprietary container — they are",
        "NOT directly usable TTFs, so no local previews can be rendered.",
        "Use `scripts/show_font_samples.py` to display fonts on the device",
        "and photograph them instead.",
        "",
        "| id | size | type | name | charset | file |",
        "|---|---|---|---|---|---|",
    ]
    for f in sorted(fonts, key=lambda f: int(f["id"])):
        fid = int(f["id"])
        charset = str(f.get("charset", "")).replace("|", "\\|")
        cell_charset = charset[:60] + ("…" if len(charset) > 60 else "")
        file_url = f.get("fontUrl") or f.get("url") or ""
        file_cell = f"[file]({CDN}{file_url})" if file_url else "—"
        lines.append(
            f"| {fid} | {f.get('width', '?')}×{f.get('high', '?')} "
            f"| {TYPE_LABELS.get(int(f.get('type', -1)), f.get('type'))} "
            f"| {str(f.get('name', '?')).replace('|', '\\|')} "
            f"| `{cell_charset}` | {file_cell} |"
        )

    path = os.path.join(out_dir, "FONTS_CATALOG.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Wrote {path} ({len(fonts)} fonts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
